version: '3.7'
services:
  leika-api:
    build:
      context: ..
      dockerfile: docker/leika_api.Dockerfile
    image: leika-api:latest
    environment:
    - ELASTIC_HOST=elasticsearch
    - ELASTIC_PORT=9200
    - ELASTIC_INDEX=leika
    depends_on:
      - leika-elasticsearch-data
    ports:
      - "80:80"
  leika-elasticsearch-data:
    image: publicplan/leika-elasticsearch-data:master
    environment:
    - NODE_ENV=dev
    - LOG_LEVEL=debug
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    - ELASTICSEARCH_INDEX_NAME=leika
    restart: on-failure
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
    environment:
      - cluster.name=elasticsearch
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:6.8.2
  #   environment:
  #     ELASTICSEARCH_URL: http://elasticsearch:9200
  #   ports:
  #     - 5601:5601
